# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gcp-python-client-functions',
                'doc_host': 'https://datasciencedani.github.io',
                'git_url': 'https://github.com/datasciencedani/gcp-python-client-functions',
                'lib_path': 'gcp_python_client_functions'},
  'syms': { 'gcp_python_client_functions.bigquery': { 'gcp_python_client_functions.bigquery.query_to_df': ( 'bigquery.html#query_to_df',
                                                                                                            'gcp_python_client_functions/bigquery.py')},
            'gcp_python_client_functions.core': { 'gcp_python_client_functions.core.foo': ( 'bigquery.html#foo',
                                                                                            'gcp_python_client_functions/core.py')}}}
