name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
        contents: 'read'
        id-token: 'write'

    steps: 
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/532579765435/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'svc-github@dz-learning-d.iam.gserviceaccount.com'
        
    - name: 'Nbdev CI'
      uses: fastai/workflows/nbdev-ci@master
